import { ValidationError } from './errors';
import type { Citation, Handover, HandoverEvent, Source, Task } from './types';

const fail = (message: string): never => { throw new ValidationError(message); };
const object = (value: unknown, name: string): Record<string, unknown> => { if (value === null || typeof value !== 'object' || Array.isArray(value)) fail(`${name} must be an object.`); return value as Record<string, unknown>; };
const fields = (value: Record<string, unknown>, allowed: readonly string[], name: string) => { for (const key of Object.keys(value)) if (!allowed.includes(key)) fail(`${name} contains unknown field ${key}.`); };
const string = (value: unknown, name: string, nonempty = false): string => { if (typeof value !== 'string' || (nonempty && value.trim() === '')) fail(`${name} must be a nonempty string.`); return value as string; };
const nullableString = (value: unknown, name: string): string | null => { if (value !== null && typeof value !== 'string') fail(`${name} must be a string or null.`); return value as string | null; };
const revision = (value: unknown, name: string): number => { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 1) fail(`${name} must be a positive safe integer.`); return value as number; };
const iso = (value: unknown, name: string): string => { const text = string(value, name); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(text) || Number.isNaN(Date.parse(text))) fail(`${name} must be an ISO UTC timestamp.`); const d = new Date(text); if (d.toISOString() !== text) fail(`${name} is not a real calendar timestamp.`); return text; };
const dateOnly = (value: unknown, name: string): string => { const text = string(value, name); if (!/^\d{4}-\d{2}-\d{2}$/.test(text)) fail(`${name} must be an ISO date.`); const [y, m, d] = text.split('-').map(Number); const actual = new Date(0); actual.setUTCHours(0, 0, 0, 0); actual.setUTCFullYear(y, m - 1, d); if (actual.getUTCFullYear() !== y || actual.getUTCMonth() !== m - 1 || actual.getUTCDate() !== d) fail(`${name} is not a real calendar date.`); return text; };
const digest = (value: unknown, name: string): string => { const text = string(value, name); if (!/^[a-f0-9]{64}$/.test(text)) fail(`${name} must be a lowercase SHA-256 digest.`); return text; };
const unique = (values: string[], name: string) => { if (new Set(values).size !== values.length) fail(`${name} contains duplicate IDs.`); };
const array = (value: unknown, name: string): unknown[] => { if (!Array.isArray(value)) fail(`${name} must be an array.`); return value as unknown[]; };

export function utf8Size(text: string): number { return new TextEncoder().encode(text).byteLength; }
export function validateSourceText(text: string): void { string(text, 'source text'); if (utf8Size(text) > 65536) fail('source text exceeds 65536 UTF-8 bytes.'); }

function validateSource(value: unknown): Source { const v = object(value, 'source'); fields(v, ['id', 'title', 'text', 'sha256', 'revision'], 'source'); const text = string(v.text, 'source.text'); validateSourceText(text); return { id: string(v.id, 'source.id', true), title: string(v.title, 'source.title', true), text, sha256: digest(v.sha256, 'source.sha256'), revision: revision(v.revision, 'source.revision') }; }
function validateCitation(value: unknown): Citation { const v = object(value, 'citation'); fields(v, ['sourceId', 'sourceRevision', 'quote'], 'citation'); return { sourceId: string(v.sourceId, 'citation.sourceId', true), sourceRevision: revision(v.sourceRevision, 'citation.sourceRevision'), quote: string(v.quote, 'citation.quote', true) }; }
function validateTask(value: unknown, sources: Source[]): Task { const v = object(value, 'task'); fields(v, ['id', 'title', 'owner', 'dueDate', 'state', 'citations', 'reviewedAt', 'provenance'], 'task'); const state = string(v.state, 'task.state'); if (!['draft', 'approved', 'rejected'].includes(state)) fail('task.state is invalid.'); const provenance = string(v.provenance, 'task.provenance'); if (!['manual', 'deterministic-suggestion', 'imported'].includes(provenance)) fail('task.provenance is invalid.'); const citations = array(v.citations, 'task.citations').map(validateCitation); citations.forEach(c => { if (!sources.some(s => s.id === c.sourceId)) fail('citation source does not exist.'); }); const reviewedAt = v.reviewedAt === null ? null : iso(v.reviewedAt, 'task.reviewedAt'); if (state === 'draft' && reviewedAt !== null) fail('draft tasks must have null reviewedAt.'); if (state !== 'draft' && reviewedAt === null) fail('approved and rejected tasks require reviewedAt.'); const task: Task = { id: string(v.id, 'task.id', true), title: string(v.title, 'task.title', true), owner: nullableString(v.owner, 'task.owner'), dueDate: v.dueDate === null ? null : dateOnly(v.dueDate, 'task.dueDate'), state: state as Task['state'], citations, reviewedAt, provenance: provenance as Task['provenance'] }; if (state === 'approved') { if (citations.length === 0) fail('approved tasks require a citation.'); citations.forEach(c => verifyCitation(sources.find(s => s.id === c.sourceId)!, c)); } return task; }
function validateEvent(value: unknown): HandoverEvent { const v = object(value, 'event'); fields(v, ['id', 'at', 'kind', 'detail'], 'event'); const kind = string(v.kind, 'event.kind'); if (!['created', 'edited', 'reviewed', 'imported', 'exported'].includes(kind)) fail('event.kind is invalid.'); return { id: string(v.id, 'event.id', true), at: iso(v.at, 'event.at'), kind: kind as HandoverEvent['kind'], detail: string(v.detail, 'event.detail') }; }

export function verifyCitation(source: Source, citation: Citation): void { if (citation.sourceId !== source.id || citation.sourceRevision !== source.revision || citation.quote.trim() === '' || !source.text.includes(citation.quote)) fail('citation does not match the current source revision and exact quote.'); }
export function validateHandover(value: unknown): Handover { const v = object(value, 'handover'); fields(v, ['id', 'title', 'organization', 'createdAt', 'updatedAt', 'sources', 'tasks', 'events', 'revision'], 'handover'); const sources = array(v.sources, 'handover.sources').map(validateSource); if (sources.length > 50) fail('handover cannot contain more than 50 sources.'); unique(sources.map(s => s.id), 'sources'); const tasks = array(v.tasks, 'handover.tasks').map(t => validateTask(t, sources)); if (tasks.length > 500) fail('handover cannot contain more than 500 tasks.'); unique(tasks.map(t => t.id), 'tasks'); const events = array(v.events, 'handover.events').map(validateEvent); unique(events.map(e => e.id), 'events'); const result: Handover = { id: string(v.id, 'handover.id', true), title: string(v.title, 'handover.title', true), organization: string(v.organization, 'handover.organization', true), createdAt: iso(v.createdAt, 'handover.createdAt'), updatedAt: iso(v.updatedAt, 'handover.updatedAt'), sources, tasks, events, revision: revision(v.revision, 'handover.revision') }; if (utf8Size(JSON.stringify(result)) > 8388608) fail('handover exceeds 8 MiB serialized size.'); return result; }
export function canonicalHandoverJson(value: unknown): string { return JSON.stringify(validateHandover(value)); }
